/*
INSTRUCTIONS

1. using promise API, i.e. only .then() .catch() and .finally() methods, consume the methods in firstnames.js and lastnames.js
2. don't use any async/await here
3. lastnames.js method expects a positive integer id, it returns a lastname, if the id is multiple of 5 it returns a nonexistent lastname
4. firstnames.js method expects a lastname generated by the method above, it returns a name
5. methods should be consumed sequentially, i.e. lastnames method first, and its results will serve as argument for firstnames method
6. implement a randomizing logic that provides you an id for lastnames method,
this value type must be a positive integer between 0-100, or something that is not a positive integer
The point here is getting correct and incorrect values to get successful and failing promises results from lastnames method

Example:
const id = yourRandomMethod() //first run
 -- id gets a value of undefined, or you can get a null, boolean, string, whatever different to a positive integer

const id = yourRandomMethod() //second run
 -- id gets a value of 31

const id = yourRandomMethod() //third run
-- id gets a value of 10

6. use promise chaining accordingly, don't forget error handling
7. log the resultant fullname, or the error, at the end
*/

function solution() {
    const getFirstName = require('./firstnames');
    const getLastName = require('./lastnames');
    let fullName = 'Full Name: ';

    const getRandomId = () =>{
        let randomizer= Math.floor(Math.random() * 10); 
        let randomString = '';
        let characters = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';
        for (let i = 0; i < 6; i++) {
            randomString += characters.charAt(Math.floor(Math.random() * characters.length));
        }
        if(randomizer <=3) //returns a number 
            return Math.floor(Math.random() * 100); 
        if(randomizer===4) //returns a boolean
            return Math.random() < 0.5;
        if(randomizer===5) //returns undefined
            return undefined;
        if(randomizer==6) //returns a random string
            return null;
        return randomString;
    }

    const id = getRandomId();
    console.log(`Testing with ID: ${id}`);
    getLastName(id)
        .then(lastName => {
            fullName+= lastName
            return getFirstName(lastName)

        })
        .then(firstName => {
            fullName += ' ' + firstName
            console.log(fullName)
        })
        .catch(err => console.log(err.message))
}

solution()
